kind: pipeline
name: default

steps:
- name: coverage
  image: brazildatacube/sits-r:latest
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - R -e ' withr::with_envvar(c(NOT_CRAN="true"), covr::codecov(quiet = FALSE))'
