# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

apply_transition_matrix <- function(data_before, data, transition_matrix) {
    .Call(`_sits_apply_transition_matrix`, data_before, data, transition_matrix)
}

max_ts <- function(mtx) {
    .Call(`_sits_max_ts`, mtx)
}

min_ts <- function(mtx) {
    .Call(`_sits_min_ts`, mtx)
}

sum_ts <- function(mtx) {
    .Call(`_sits_sum_ts`, mtx)
}

mean_ts <- function(mtx) {
    .Call(`_sits_mean_ts`, mtx)
}

std_ts <- function(mtx) {
    .Call(`_sits_std_ts`, mtx)
}

skew_ts <- function(mtx) {
    .Call(`_sits_skew_ts`, mtx)
}

kurt_ts <- function(mtx) {
    .Call(`_sits_kurt_ts`, mtx)
}

amplitude_ts <- function(mtx) {
    .Call(`_sits_amplitude_ts`, mtx)
}

fslope_ts <- function(mtx) {
    .Call(`_sits_fslope_ts`, mtx)
}

abs_sum_ts <- function(mtx) {
    .Call(`_sits_abs_sum_ts`, mtx)
}

amd_ts <- function(mtx) {
    .Call(`_sits_amd_ts`, mtx)
}

mse_ts <- function(mtx) {
    .Call(`_sits_mse_ts`, mtx)
}

fqr_ts <- function(mtx) {
    .Call(`_sits_fqr_ts`, mtx)
}

tqr_ts <- function(mtx) {
    .Call(`_sits_tqr_ts`, mtx)
}

sqr_ts <- function(mtx) {
    .Call(`_sits_sqr_ts`, mtx)
}

iqr_ts <- function(mtx) {
    .Call(`_sits_iqr_ts`, mtx)
}

row_wide_loop <- function(x) {
    .Call(`_sits_row_wide_loop`, x)
}

bayes_smoother <- function(m, m_nrow, m_ncol, w, sigma, covar_sigma0) {
    .Call(`_sits_bayes_smoother`, m, m_nrow, m_ncol, w, sigma, covar_sigma0)
}

kernel_smoother <- function(m, m_nrow, m_ncol, w, normalised) {
    .Call(`_sits_kernel_smoother`, m, m_nrow, m_ncol, w, normalised)
}

bilinear_smoother <- function(m, m_nrow, m_ncol, w, tau) {
    .Call(`_sits_bilinear_smoother`, m, m_nrow, m_ncol, w, tau)
}

median_neigh <- function(data, nrows_window, ncols_window) {
    .Call(`_sits_median_neigh`, data, nrows_window, ncols_window)
}

cbers4_cld_detect <- function(b13, b14, b15, b16, thres_1, t2, t3, t4, t5, t6, values) {
    .Call(`_sits_cbers4_cld_detect`, b13, b14, b15, b16, thres_1, t2, t3, t4, t5, t6, values)
}

cbers4_cld_values <- function(b13, b14, b15, b16) {
    .Call(`_sits_cbers4_cld_values`, b13, b14, b15, b16)
}

linear_interp <- function(mtx) {
    .Call(`_sits_linear_interp`, mtx)
}

linear_interp_vec <- function(vec) {
    .Call(`_sits_linear_interp_vec`, vec)
}

normalize_data <- function(data, min, max) {
    .Call(`_sits_normalize_data`, data, min, max)
}

normalize_scale_data <- function(data) {
    .Call(`_sits_normalize_scale_data`, data)
}

